version: '3'
services:
  # Don't worry about environment variables here; it's using the .env file at
  # the root of the project
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
    volumes:
      - ./:/myapp
    ports:
      - "3000:3000"
    env_file:
      - .env
